---
title: "Datenaufbereitung"
author: "Stefan P. Thoma"
date: "3/2/2020"
output: html_document
---

# Setup

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
if (!require("pacman")) install.packages("pacman")
p_load(tidyverse)
```

# Load Data

```{r}
master <- read_csv("Master/masterData.csv")
exp_uebung <- read_csv("ExperimentelleUebung/Exp_Data.csv")
```
```{r}
names(master)

names(exp_uebung)
```

```{r}

master <- master %>% 
  mutate(Leiter = "Stefan",
        sex = ifelse(sex == 1, "W", "M"))
exp_uebung <- exp_uebung %>% 
  rename(sex = Geschlecht)

namesInExp <- names(exp_uebung)
namesInMaster <- names(master)
namesInMasterNotInExp <- namesInMaster[!namesInMaster %in% namesInExp]
namesInExpNotInMaster <- namesInExp[!namesInExp %in% namesInMaster]

master[namesInExpNotInMaster] <- NA
exp_uebung[namesInMasterNotInExp] <- NA

namesInMaster <- names(master)

# make order the same for exp_uebung
exp_uebung <- exp_uebung %>%
  select(all_of(namesInMaster))
```

```{r}
data <- bind_rows(exp_uebung, master)
```

```{r}
data <- data %>% select(-`sex_3_TEXT - Topics`)
write_csv(data, "allData.csv")
```


