---
title: "clean and merge"
author: "Stefan Thoma"
date: "1/13/2020"
output: html_document
---

# Setup

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
if (!require("pacman")) install.packages("pacman")
p_load(tidyverse,  stringr, dataMaid)
```

# Load Data

```{r load data}
T1_desc <- read_csv("data/T1_exp.csv")[1,]
T2_desc <- read_csv("data/T2_exp.csv")[1,]
T2_desc <- T2_desc %>% rename(pol = Q84)
T1_data <- read_csv("data/T1_exp.csv")[-c(1,2),]
T2_data <- read_csv("data/T2_exp.csv")[-c(1,2),]
```
```{r sort columns}

### T1
# add T vector
T1_data$time <- 1

want1 <- names(T1_data)[c(83, 84, 7, 18:82)]
# see which ids are valid
T1_valID <- T1_data$id[str_detect(T1_data$id, pattern = "[A-Za-z]{4,}[0-9]{2,}" ) & !is.na(T1_data$id)]


T1_data <- T1_data %>% 
  select(want1)


# use only ids that are valid
T1_data <- filter(T1_data, id %in%T1_valID)


# T2
# add T vector
T2_data$time <- 2

names(T2_data)
want2 <- names(T2_data)[c(129, 133, 130, 7, 18:128)]


# see which ids are valid
T2_valID <- T2_data$id[str_detect(T2_data$id, pattern = "[A-Za-z]{4,}[0-9]{2,}" ) & !is.na(T2_data$id)]

T2_data <- T2_data %>% 
  select(want2, -sex_2_TEXT) %>%
  rename(pol = Q84,
         )

# use only ids that are valid
T2_data <- filter(T2_data, id %in%T2_valID)
T2_data$id
```
fix column names 
```{r}
# create col names
old_names <- paste("Q89", 1:17, sep = "_")
new_names <- paste("SES", 1:17, sep = "_")
# rename
names(T2_data)[names(T2_data) %in% old_names] <- new_names


# now fix VR-Eval
vr_eval <- T2_data %>% select(id, starts_with("vr"))

vr_eval_delete <- paste("vr_eval", 1:5, "_", rep(1:2, each = 5), sep = "")

vr_eval_delete <- vr_eval_delete[!vr_eval_delete %in% c(paste("vr_eval", c(2,4), "_2", sep = ""))]
delete_columns <- c(vr_eval_delete, "tb_seen", "tb_span", "rem_ipq")
T2_data <- T2_data %>%
  mutate(vr_eval1 = ifelse(!is.na(vr_eval1), vr_eval1, 
                           ifelse(!is.na(vr_eval1_1), vr_eval1_1, vr_eval1_2)),
         
         
         
         vr_eval2 = ifelse(!is.na(vr_eval2), vr_eval2, vr_eval2_1),
#                           ifelse(!is.na(vr_eval2_1), vr_eval2_1, vr_eval2_2)),
         vr_eval3 = ifelse(!is.na(vr_eval3), vr_eval3, 
                           ifelse(!is.na(vr_eval3_1), vr_eval3_1, vr_eval3_2)),
         vr_eval4 = ifelse(!is.na(vr_eval4), vr_eval4, vr_eval4_1),
#                           ifelse(!is.na(vr_eval4_1), vr_eval4_1, vr_eval4_2)),
         vr_eval5 = ifelse(!is.na(vr_eval5), vr_eval5, 
                           ifelse(!is.na(vr_eval5_1), vr_eval5_1, vr_eval5_2)), 
         span = ifelse(!is.na(span), span, tb_span),
         seen = ifelse(!is.na(seen), seen, tb_seen)

         ) %>%
  select(-delete_columns)
```
merge
```{r}
data <- merge(T2_data, T1_data, all = TRUE) 

# create a vector with only values that are not duplicated
uniq <- data$id[!data$id %in% data$id[duplicated(data$id)] ]

data <- data %>% filter(Finished==1, id!=uniq, id!="AREF98")
booth <- names(T2_data)[c(3, 5:38)]
data <- data %>% group_by(id) %>%
  mutate(condition = condition[time==2],
         age = age[time==2],
         edu = edu[time==2],
         sex = sex[time==2],
         pol = pol[time==2],
         sod_1 = sod_1[time==2],
         sod_2 = sod_2[time==2],
         sod_3 = sod_3[time==2],
         sod_4 = sod_4[time==2],
         sod_5 = sod_5[time==2],
         sod_6 = sod_6[time==2],
         sod_7 = sod_7[time==2],
         sod_8 = sod_8[time==2],
         sod_9 = sod_9[time==2],
         vr_eval1 = vr_eval1[time==2],
         vr_eval2 = vr_eval2[time==2],
         vr_eval3 = vr_eval3[time==2],
         vr_eval4 = vr_eval4[time==2],
         vr_eval5 = vr_eval5[time==2],
         span = span[time==2],
         seen = seen[time==2],
         ipq1 = ipq1[time==2],
         ipq2 = ipq2[time==2],
         ipq3 = ipq3[time==2],
         ipq4 = ipq4[time==2],
         ipq5 = ipq5[time==2],
         ipq6 = ipq6[time==2],
         ipq7 = ipq7[time==2],
         ipq8 = ipq8[time==2],
         ipq9 = ipq9[time==2],
         ipq10 = ipq10[time==2],
         ipq11 = ipq11[time==2],
         ipq12 = ipq12[time==2],
         ipq13 = ipq13[time==2],
         ipq14 = ipq14[time==2]
         ) %>%
  ungroup()
```

# add iat data

```{r}
iat <- read_csv("iat_result.csv") %>% 
  rename(id = participant) %>%
  mutate(time = as.numeric(as.character(time)))

data <- merge(data, iat)
```
# add organisation data
```{r}
org <- read_csv("organisationData.csv")
org <- org %>% select(
  ID, Leiter, Condition, Anmerkungen, Zeit, starts_with("Frage"), Geschlecht, Alter
) %>%
  rename(id = ID) 

data <- merge(data, org) %>%
  select(-Alter, -sex, -Finished)

selection <- names(data)[c(1:2, 68:71, 86:87, 103:104, 110)]

#final reorder

data <- data %>% 
  select(selection, names(data)[!names(data)%in%selection], -Condition)

```
```{r}
for(i in unique(data$id)){
    randNum <- i
    while(randNum %in% data$id){
      randNum <- paste(sample(0:9, 8, replace = TRUE), collapse = "" )}
    data$id[data$id==i] <- randNum
}
```


```{r}
write_csv(data, "Exp_Data.csv")
#dataMaid::makeCodebook(data, file = "codebook_data")
```



