---
title: "Bind IAT"
author: "Stefan"
date: "9 4 2019"
output: html_document
---

# Setup
```{r setup}
pacman::p_load(tidyverse, magrittr, ggplot2)
source("iat_function.R")
```

# Data
```{r load data, warning=FALSE, message = FALSE}
path_to_data <- paste(getwd(), "/data/iat", sep = "")

temp <- list.files(path = path_to_data, pattern="*.csv")
temp <-paste(path_to_data, temp, sep = "/")



csv <- function(x){
  
  y <- read_csv2(x) %>% 
  mutate(participant = as.character(participant))
  
  
# y <- read_csv2(x) %>%
#   mutate(participant = as.character(participant))
  return(y)
}


iat_data <- lapply(temp, csv) %>%
  bind_rows()
# here we replace the participant id 1715364 with the participant id 17101993, 
# because of a data entry error. 
iat_data <- iat_data %>%
  filter(!is.na(Word)) %>%
  select(c("participant", names(iat_data))[!duplicated(c("participant", names(iat_data)))], -X17)# %>%
 # mutate(participant = ifelse(participant == "17101993", "17153164", participant), 
 #        participant = ifelse(participant == "07114689", "07114687", participant), 
 #        participant = ifelse(participant == "14134935", "14134936", participant), 
 #        )

```

```{r get iat result}
n_participants <- length(unique(iat_data$participant))

result_long <- data.frame(participant = rep(levels(as.factor(iat_data$participant)), each = 2), time = rep(c("001", "002"), times = n_participants), iat = NA)

for(i in levels(as.factor(iat_data$participant))){
  for(j in c("001", "002")){
     result_long$iat[result_long$participant == i & result_long$time == j] <- iat(iat_data %>% filter(participant == i, session == j))
    print(j)
  }
  print(i)
}

```


# Save as csv
```{r write}
#write_csv(iat_data, "iat_raw.csv")
write_csv(result_long, "iat_result.csv")
```


```{r, eval = FALSE}
interested <- c("ARAR65", "ARDR97", "ARDS53", "ARHL00", "ARSW00", "FSLK99", "NSAS99", "NSDS65", "NSGC98", "NSGS90")

for(i in interested){
  PARTICIPANT <- i
  
  
  interested_plot <- ggplot(data = result_long, aes(x = as.numeric(as.character(time)), y = iat, color = participant)) + 
  geom_line(alpha = .3, show.legend = FALSE)+
  geom_smooth(method = "lm", aes(x = as.numeric(as.character(time)), y = iat), inherit.aes = FALSE, alpha = .5) +
  geom_line(data = result_long %>% filter(participant == PARTICIPANT), color = "black") +
  ggtitle(paste("IAT score: Thick blue is mean, black is participant ", i))+
  scale_x_discrete( limits=c("0","1")) + 
  ggthemes::theme_tufte()
 
  
  
  ggsave(paste("plots/IATPlot_", i), plot = interested_plot, device = "png") 
}


result_long
```


