---
title: "Bind IAT"
author: "Stefan"
date: "9 4 2019"
output: html_document
---

# Setup
```{r setup}
pacman::p_load(tidyverse, limma, IATScore, magrittr, ggplot2)
```

# Participant of interest
```{r, eval = FALSE}
PARTICIPANT <- "17121534"
```

# Data
```{r load data, warning=FALSE, message = FALSE}
path_to_data <- paste(getwd(), "/iat_data", sep = "")

temp <- list.files(path = path_to_data, pattern="*.csv")
temp <-paste(path_to_data, temp, sep = "/")

csv <- function(x){
  y <- read_csv2(x) %>%
    mutate(participant = as.character(participant))
  return(y)
}


iat_data <- lapply(temp, csv) %>%
  bind_rows()
# here we replace the participant id 1715364 with the participant id 17101993, 
# because of a data entry error. 
iat_data <- iat_data %>%
  filter(!is.na(Word)) %>%
  select(c("participant", names(iat_data))[!duplicated(c("participant", names(iat_data)))], -X17) %>%
  mutate(participant = ifelse(participant == "17101993", "17153164", participant), 
         participant = ifelse(participant == "07114689", "07114687", participant), 
         participant = ifelse(participant == "14134935", "14134936", participant), 
         )

```




## Get in shape

```{r get data in shape}
iat_data %<>% 
  mutate(rt = 1000*as.numeric(key_resp_2.rt),
         incorrect = (as.numeric(key_resp_2.corr)-1)^2,
         participant = as_factor(participant))
iat_selected <- iat_data %>% 
  select(
    participant, session,  Block, trials.thisTrialN, Category, trials.thisIndex, incorrect, rt) %>%
  rename(X1 = Block, X2 = trials.thisTrialN, X3 = Category, X4 = trials.thisIndex, X5 = incorrect, X6 = rt)
names(iat_data)


result <- data.frame(participant = levels(iat_selected$participant),
                     iat_t1 = NA,
                     iat_t2 = NA)
```

```{r}
n_participants <- length(unique(iat_data$participant))
source("iat_function.R")
result_long <- data.frame(participant = rep(levels(as.factor(iat_data$participant)), each = 2), time = rep(c("001", "002"), times = n_participants), iat = NA)


for(i in levels(as.factor(iat_data$participant))){
  for(j in c("001", "002")){
     result_long$iat[result_long$participant == i & result_long$time == j] <- iat(iat_data %>% filter(participant == i, session == j))
    print(j)
  }
  print(i)
}
result_long

```




# Save as csv
```{r write}
write_csv(result_long, "iat_result.csv")
```



