---
title: "Bind IAT"
author: "Stefan"
date: "9 4 2019"
output: html_document
---

# Setup
```{r setup}
pacman::p_load(tidyverse, limma, IATScore, magrittr, ggplot2)
```

# Participant of interest
```{r}
PARTICIPANT <- "17121534"
```

# Data
```{r load data, warning=FALSE, message = FALSE}
path_to_data <- paste(getwd(), "/iat_data", sep = "")

temp <- list.files(path = path_to_data, pattern="*.csv")
temp <-paste(path_to_data, temp, sep = "/")

csv <- function(x){
  y <- read_csv2(x) %>%
    mutate(participant = as.character(participant))
  return(y)
}


iat_data <- lapply(temp, csv) %>%
  bind_rows()
# here we replace the participant id 1715364 with the participant id 17101993, 
# because of a data entry error. 
iat_data <- iat_data %>%
  filter(!is.na(Word)) %>%
  select(c("participant", names(iat_data))[!duplicated(c("participant", names(iat_data)))], -X17) %>%
  mutate(participant = ifelse(participant == 17101993, 17153164, participant))

```

## Get in shape

```{r get data in shape}
iat_data %<>% 
  mutate(rt = 1000*as.numeric(key_resp_2.rt),
         incorrect = (as.numeric(key_resp_2.corr)-1)^2,
         participant = as_factor(participant))
iat_selected <- iat_data %>% 
  select(
    participant, session,  Block, trials.thisTrialN, Category, trials.thisIndex, incorrect, rt) %>%
  rename(X1 = Block, X2 = trials.thisTrialN, X3 = Category, X4 = trials.thisIndex, X5 = incorrect, X6 = rt)
names(iat_data)




IATScore::BriefIAT

result <- data.frame(participant = levels(iat_selected$participant),
                     iat_t1 = NA,
                     iat_t2 = NA)
for(j in result$participant){
result$iat_t1[result$participant==j] <- iat_selected %>% filter(participant == j, session == "001") %>%
  select(-participant, -session) %>%
  IATScore(Trials = 180)

result$iat_t2[result$participant==j] <- iat_selected %>% filter(participant == j, session == "002") %>%
  select(-participant, -session) %>%
  IATScore(Trials = 180)
}

mean(result$iat_t1)
mean(result$iat_t2)
```

```{r wide to long}
result_long <- result %>%
  gather(time, iat, c("iat_t1", "iat_t2"))%>%
  mutate(time = ifelse(time == "iat_t1", 1, 2))
```
# Plot
```{r}
ggplot(data = result_long, aes(x = time, y = iat, color = participant)) + 
  geom_line(alpha = .3)+
  geom_smooth(method = "lm", aes(x = time, y = iat), inherit.aes = FALSE, alpha = .5) +
  geom_line(data = result_long %>% filter(participant == PARTICIPANT), color = "black") +
  ggthemes::theme_tufte()
```


# Save as csv
```{r save}
write_csv(iat_data, "iat_raw.csv")
write_csv(result_long, "iat_result.csv")
```


# Analysis
```{r}
t.test(result_long$iat ~ result_long$time)
```




