---
title: "heartRate"
author: "Stefan P. Thoma"
date: "7/13/2019"
output: html_document
---
# Setup
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

pacman::p_load(tidyverse, ggplot2, readxl, data.table, hms)
```

# Load data

```{r load data}
# first, the excel transcript file with the hear rate information
info_raw <- read_excel("open/transcript.xlsx", ) 
info_raw <- info_raw %>% select(`participant nr.`, ID, date, baseStart, baseEnd, vrStart, vrEnd, Frage1, Frage2, Frage3) %>%
  mutate(baseStart = as.hms(format(baseStart, format = "%H:%M:%S")), # these lines drop the dates and leave time only.
         baseEnd = as.hms(format(baseEnd, format = "%H:%M:%S")),
         vrStart = as.hms(format(vrStart, format = "%H:%M:%S")),
         vrEnd = as.hms(format(vrEnd, format = "%H:%M:%S")), 
         date = format(date, format = "%d.%m.%y"))
info <- info_raw %>% drop_na()

```
```{r load heart rate data}
# find all csv files that start with "Fitbit" and end in ".csv"
temp <- list.files(patter = ".csv")
temp <- temp[temp %>% startsWith("Fitbit")]

hr_data <- map(temp, read_csv) %>%
  bind_rows() %>%
  mutate(id = NA,
         t = NA
         )
```
# Assign correct ID

```{r assign ID and delete all data not assigned}
for(i in info$ID){
    hr_data$id[hr_data$Date == info$date[info$ID == i] & hr_data$time >= info$baseStart[info$ID == i] & hr_data$time <= info$baseEnd[info$ID == i]] <- i
    hr_data$t[hr_data$Date == info$date[info$ID == i] & hr_data$time >= info$baseStart[info$ID == i] & hr_data$time <= info$baseEnd[info$ID == i]] <- 1
    hr_data$id[hr_data$Date == info$date[info$ID == i] & hr_data$time >= info$vrStart[info$ID == i] & hr_data$time <= info$vrEnd[info$ID == i]] <- i
    hr_data$t[hr_data$Date == info$date[info$ID == i] & hr_data$time >= info$vrStart[info$ID == i] & hr_data$time <= info$vrEnd[info$ID == i]] <- 2
}
hr_data_reduced <- hr_data %>% drop_na
```
# Get mean per person
```{r}
hr_mean <- hr_data_reduced %>% group_by(id, t) %>%
  mutate(hr_mean=mean(value)) %>%
  select(-value, -time) %>%
  distinct()
hr_open_data <- merge(hr_mean, info_raw)
glimpse(hr_open_data)
```

```{r bind together}
write.csv(hr_open_data, "hr_open_data.csv")
```

